### PR TITLE
Eamena 27 bulk upload view - with appended files

### PR DESCRIPTION
**Pull request by TeriForey**
### Description of Change

Based on the bulk upload view (#27), I've added in functionality to identify the resource IDs, upload a whole directory and then edit each resource to contain the uploaded file contents. 

### Issues Solved

#29 , https://github.com/azerbini/eamena_v3/issues/60

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### Further comments

Added an option to the packages load_resources operation that if running internally it outputs a dictionary containing the old and new resource IDs. This is then picked up in the bulk_upload views and is used to retrieve the relevant resource per uploaded file. For each file within the uploaded folder, the arches file is searched to see if it contains that file name, the new resource ID is identified and the resource is updated (including making a thumbnail). If there are files in the uploaded folder that don't correspond to anything in the arches file then these are skipped. If we can't identify the resource ID, then we report an error - but note that the resource has already been saved with a file that doesn't exist. Also, as there are now two file upload widgets on the same page I can't get them to run completely independently. The first upload (excel spreadsheet) runs both upload views and I don't know how to stop it doing that. Someone with more javascript experience will probably be able to fix it.

### CODE REVIEW

**Comment by mradamcox** [comment]
@TeriForey and @azerbini I wanted to test this out so I resolved the conflicts. Going to test locally now.

**Comment by mradamcox** [comment]
@TeriForey is there any way you could add some example data to this thread (maybe just a zipfile) so that others can test the new file upload capability with Information Resources?

**Comment by TeriForey** [comment]
I’m away this week but will upload an example on Monday when I’m back.

Sent from my iPhone

On 9 Jul 2018, at 21:04, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


@TeriForey<https://github.com/TeriForey> is there any way you could add some example data to this thread (maybe just a zipfile) so that others can test the new file upload capability with Information Resources?

**Comment by TeriForey** [comment]
@mradamcox sorry for the delay while I was away. Here's a very simple example excel spreadsheet and folder containing two image files:
[EAMENA_fileupload.tar.gz](https://github.com/azerbini/eamena_dev/files/2197192/EAMENA_fileupload.tar.gz)

**Comment by mradamcox** [comment]
Tested locally with the attachment above, works great.

**Review by mradamcox — COMMENTED** [review]
works well locally, merging now.

**Pull request merged**
