### PR TITLE
Eamena 27 bulk upload view

### PR DESCRIPTION
**Pull request by mradamcox**
This is a big overhaul of the Excelreader command, which splits all of the validation functions into standalone operations. This is paired with a new strategy for chaining ajax calls to each of these validation functions, which simulates an asynchronous user experience, with feedback coming to the UI each time a specific function completes.

Refactoring the Excelreader command allowed for some improvements in efficiency. For example, validating the concepts in a 200 resource input file used to take 6 minutes, and now takes 2 seconds.

This PR does not yet address the load wait a user would experience during the actual import of the data, only during the validation operations.

Issues addressed:
https://github.com/azerbini/eamena_v3/issues/60
https://github.com/azerbini/eamena_dev/issues/27

### CODE REVIEW

**Comment by mradamcox** [comment]
@azerbini it looks like the only conflict is in some of the opt parse arguments in packages.py, which I didn't need to change at all for this PR. Could you please resolve those conflicts? I have a feeling it's related to migration work you've been doing.

**Comment by azerbini** [comment]
Will do, and yes it is related to the migration work. Will you be pushing other commits to address the data load? I will be testing this tomorrow with a dataset of ca. 2000 resources (normal use case for EAMENA) and will let you know how it works.


Sent from my iPhone

On 13 Sep 2018, at 21:28, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


@azerbini<https://github.com/azerbini> it looks like the only conflict is in some of the opt parse arguments in packages.py, which I didn't need to change at all for this PR. Could you please resolve those conflicts? I have a feeling it's related to migration work you've been doing.

**Comment by mradamcox** [comment]
@azerbini sorry for the late reply. I would like to get this merged in before addressing the data loading, b/c the current work in is a complete state.

**Comment by azerbini** [comment]
screen shot 2018-09-23 at 15 00 12

@mradamcox, rows_and_values test seems to fail all the time in spite of the number of | separated values being equal. I am emailing you the XLSX I used for this test.

**Comment by mradamcox** [comment]
@azerbini found a few issues. Essentially, there are blank columns and blank rows in the excel file that threw off the prior validation. I've committed changes to some of the strategies and improved the error reporting, so this should be easier to deal with in the future. The file you sent, however, did have "number of values" errors, as you can see with the new error output.
image

**Comment by azerbini** [comment]
@mradamcox  this is great, thanks. I am now trying to load Teri's sample of Information resources with appended files. The sample upload XLSX validates fine, but the *.arches file outputted contains `HERITAGE_RESOURCE_GROUP.E27` instead of `INFORMATION_RESOURCE.E73` as would be expected when I select Information Resource from the type dropdown

**Comment by azerbini** [comment]
@mradamcox commit 096b63b fixes the problem referred to in my comment. I am now ready to merge this PR.

**Comment by mradamcox** [comment]
Ok, great, good catch. Thanks!

**Pull request merged**
