### PR TITLE
rename travis config to deactivate travis CI until tests are functional

### PR DESCRIPTION
**Pull request by mradamcox**
Because travis CI has always been failing, I tried running the unit tests locally, and found quite a few errors, in some cases having to do with the EAMENA-specific changes that have been made to the core Arches code.

However, note that we recently did this for the stable/3.x branch of the main Arches repo also https://github.com/archesproject/arches/pull/3264, because apparently travis was never successfully set up for that the v3 branch.

All of this to say, but renaming this file we will no longer trigger travis builds, so each PR will not be accompanied by a failing grade.

The first step in reinstating Travis CI would be to fix up all the unit tests so they work locally. You can test this locally easily (preferably with a _different_ elasticsearch instance running than you usually have) by running this command:

`python manage.py test tests --pattern=".py" --settings="tests.test_settings"`

### CODE REVIEW

**Comment by azerbini** [comment]
Hi Adam, I can also simply deactivate Travis on the repo until we are sure that it builds correctly.

Sent from my iPhone

On 25 Apr 2018, at 21:11, mradamcox <notifications@github.com<mailto:notifications@github.com>> wrote:


Because travis CI has always been failing, I tried running the unit tests locally, and found quite a few errors, in some cases having to do with the EAMENA-specific changes that have been made to the core Arches code.

However, note that we recently did this for the stable/3.x branch of the main Arches repo also archesproject#3264<https://github.com/archesproject/arches/pull/3264>, because apparently travis was never successfully set up for that the v3 branch.

All of this to say, but renaming this file we will no longer trigger travis builds, so each PR will not be accompanied by a failing grade.

The first step in reinstating Travis CI would be to fix up all the unit tests so they work locally. You can test this locally easily (preferably with a different elasticsearch instance running than you usually have) by running this command:

python manage.py test tests --pattern=".py" --settings="tests.test_settings"

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/azerbini/eamena_dev/pull/7

Commit Summary

  *   rename travis config to deactivate travis CI until tests are functional

File Changes

  *   R .travis-WIP.yml<https://github.com/azerbini/eamena_dev/pull/7/files#diff-0> (0)

Patch Links:

  *   https://github.com/azerbini/eamena_dev/pull/7.patch
  *   https://github.com/azerbini/eamena_dev/pull/7.diff

**Comment by mradamcox** [comment]
@azerbini that would work just fine too, and would probably be cleaner.

**Comment by mradamcox** [comment]
However, keep in mind that if this repo is eventually used for v4 development (where the tests are functional and Travis CI should be implemented) we'll have to go to a solution like renaming the config to disable travis only for specific branches.

**Comment by azerbini** [comment]
I have now deactivated Travis on this repo, until we sort out how to make it work properly on v3. Closing for now.

**Pull request closed without merging**
